# mkdocs.yml

site_name: 旭町MBC 運営マニュアル
theme:
  name: material
  language: ja
  # ▼ ここに追記します ▼
  logo: assets/logo.png    # 画面左上のロゴに設定
  favicon: assets/logo.png # ブラウザのタブのアイコンに設定
  # ▲ ここまで ▲
  palette:
    primary: indigo
    accent: deep orange
  features:
    - navigation.tabs
    # ... (他の設定はそのまま) ...
